server:
  port: 9082
management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  jpa:
    database-platform: za.co.magma.cmsproject.utils.SQLDialect
    hibernate:
      ddl-auto: update


  datasource:
    url: jdbc:sqlite:sqlitesample.db
    driver-class-name: org.sqlite.JDBC
    initialization-mode: always

#    username: admin
#    password: admin
  freemarker:
    suffix: .ftl